// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgSwCjJuzz9puX0Cv1VOHMKR6dSEZDU3s',
    appId: '1:807581777212:web:eea0008cbbdb0b82c53239',
    messagingSenderId: '807581777212',
    projectId: 'brahmsnexus',
    authDomain: 'brahmsnexus.firebaseapp.com',
    storageBucket: 'brahmsnexus.firebasestorage.app',
    measurementId: 'G-93P607X88M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlw5wp8i9FMriIyINmc4dqcJsvEhDjr5s',
    appId: '1:807581777212:android:3eb5ad6e8cc98f9ec53239',
    messagingSenderId: '807581777212',
    projectId: 'brahmsnexus',
    storageBucket: 'brahmsnexus.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAGfeOLK-_TrUWRW5Y7vkG3gq928TUgUA',
    appId: '1:807581777212:ios:b4119b607b3b3b68c53239',
    messagingSenderId: '807581777212',
    projectId: 'brahmsnexus',
    storageBucket: 'brahmsnexus.firebasestorage.app',
    iosBundleId: 'brahmsnexus',
  );
}
